<<<<<<< HEAD
theme: minima
title: Learning how to make my own blog
author: Sebastian Gilbert
description: What could possibly go wrong?
=======
theme: minima
title: Learning how to make my own blog
author: Sebastian Gilbert
description: What could possibly go wrong?
>>>>>>> 77baf036834b7a7d895dd5076f250704d7441c7b
